FROM rockylinux:9

RUN dnf install -y 'dnf-command(config-manager)' && \
    dnf config-manager --set-enabled crb && \
    dnf install -y epel-release && \
    dnf install -y et

COPY --chmod=755 container-entrypoint /bin/container-entrypoint

ENTRYPOINT ["/bin/container-entrypoint", "client"]
